server:
  servlet:
    context-path: /bookstore
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-server/realms/bookstore-realm
          jwk-set-uri: http://localhost:9000/realms/bookstore-realm/protocol/openid-connect/certs

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    org.springframework.security: DEBUG