server:
  servlet:
    context-path: /account-management
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/bookstore-account-management
    username: postgres
    password: postgres
    initialization-mode: always
    initialize: true
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    password: guest
    username: guest
    port: 5672
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:9000/realms/bookstore-realm
          jwk-set-uri: http://${KEYCLOAK_HOST}:9000/realms/bookstore-realm/protocol/openid-connect/certs

keycloak-server:
  host: http://${KEYCLOAK_HOST}:8080
  admin-cli:
    password: KHwj9kZE1UZ4PSSfvIfoyiVTvpdjyjrP
  user-management-client:
    password: toY1WyJlNt0jUAmTJ2UalDLVGDacI3Y4

queue-names:
  delete-user: q.delete-user

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    org.springframework.security: DEBUG