server:
  servlet:
    context-path: /catalog
  port: 8083

spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/bookstore-catalog
    username: postgres
    password: postgres
    initialization-mode: always
    initialize: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bookstore-realm
          jwk-set-uri: http://${KEYCLOAK_HOST}:8080/realms/bookstore-realm/protocol/openid-connect/certs
  redis:
    host: ${REDIS_HOST}
    port: 6379
  cache:
    redis:
      time-to-live: 60000

feign:
  account-management:
    address: http://${ACCOUNT_MANAGEMENT_HOST}:8081/account-management
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    org.springframework.security: DEBUG